### ISSUE TITLE
EZBoard lite v1.2 - Klipper SDCard updates

### ISSUE THREAD

**Issue by Hesi-Re** [th3dstudio/ezboard-klipper-stuff#1]
I just discovered that it’s possible to update firmware via SD Card on Klipper after Klipper has been initially flashed to a controller. This can be very helpful if a board is mounted in a location that is difficult to access or if you need to update firmware often. Klipper calls this SDCard updates. We just need de controller specs for this to work. Is it possible to share this info (mcu, spi_bus, cs_pin, spi_pins) or just add this board to ./scripts/flash-sdcard.sh?

https://www.klipper3d.org/SDCard_Updates.html

**Comment by houseofbugs** [comment]
The MCU is a LPC1769, which is documented in the config files already. You should be checking the examples in this repo. We also have the full pins file from our Marlin branch here: https://github.com/th3dstudio/UnifiedFirmware/blob/2.0.x/Firmware/Marlin/src/pins/lpc1769/pins_TH3D_EZBOARD.h

The things you are asking for are already documented. Do note that if you override the bootloader on the board with an incorrect flash you will need a programmer and soldering iron to reprogram the board.

Here are the pins for the SD taken from the Marlin pins file. We don't officially support Klipper so this is all I'll be able to provide. Any further pin numbers will be located in the pins file linked above. 

#define SD_SCK_PIN                         P0_07
#define SD_MISO_PIN                        P0_08
#define SD_MOSI_PIN                        P0_09
#define ONBOARD_SD_CS_PIN                  P0_06

I'm not familiar with that sd script so you should contact the Klipper Discord for help with that. Looking at the docs I'd try using the software spi if SSP1 doesn't work. You can also cross reference the pins for the board to the datasheet to see what each pin does/is capable of: https://www.nxp.com/docs/en/data-sheet/LPC1769_68_67_66_65_64_63.pdf

![image](https://user-images.githubusercontent.com/25088191/165576616-5563d9b2-706a-44ac-b005-ab4cec4108fa.png)
