### ISSUE TITLE
Klipper on V2 on Ender 5 Plus Endstop x still triggered after retract

### ISSUE THREAD

**Issue by rashecko** [th3dstudio/ezboard-klipper-stuff#3]
This issue has been resolved but gave me an extreme headache so I wanted to post here in case someone else runs into the same issue I had. The example config is a generic setup so every line still has to meet your needs for your printer. Pin numbers are accurate to the board so the numbers don't need to be changed. I put a BL touch on mine so I had to fill out the offsets on that section and change the endstop_pin to endstop_pin: probe:z_virtual_endstop so that it would work properly. As soon as I hit home the bed moved up a tiny bit I got an error stating Endstop x still triggered after retract. I ran the command QUERY_ENDSTOPS and saw that the end stops were triggered when they were not triggered and the BL touch was open when the probe was up or down. The fix for this was to remove the ! from the X and Y endstop_pin, then you have to add a ! to the dir_pin. If you don't add the ! to the dir_pin it will cause everything to go backwards instead of home correctly. With these changes everything worked as it should.

**Comment by emersonsc** [comment]
since this is resolved, please close the ticket
